/**
 * [LAYER: INFRASTRUCTURE]
 * Seed data for WoodBine Stories — vendor spotlights, visit guides, and hall news.
 */

export const BLOG_AUTHORS = [
  {
    id: 'auth-1',
    name: 'Maya Chen',
    bio: 'WoodBine editorial lead. Writes about vendors, neighborhood food, and life in the hall.',
    role: 'Editorial Director',
    avatarUrl: '/assets/generated/sarah_strategist_avatar_1778177148101.png',
    socialLinks: { twitter: '#', instagram: '#' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'auth-2',
    name: 'Jordan Ellis',
    bio: 'Former restaurant critic covering Salt Lake\'s arts district and food hall culture.',
    role: 'Food Writer',
    avatarUrl: '/assets/generated/leonardo_dabee_avatar_1778177134928.png',
    socialLinks: { twitter: '#', instagram: '#' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'auth-3',
    name: 'Sam Ortiz',
    bio: 'Events and community manager at WoodBine — private bookings, live nights, and vendor onboarding.',
    role: 'Community Manager',
    avatarUrl: '/assets/generated/professor_oak_avatar_1778177162886.png',
    socialLinks: { twitter: '#', instagram: '#' },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const BLOG_SERIES = [
  {
    id: 'ser-1',
    title: 'Vendor Spotlights',
    slug: 'vendor-spotlights',
    description: 'Meet the counters, chefs, and makers who fill the hall with new flavors.',
    categoryIds: ['vendor-spotlights'],
    articleCount: 2,
    difficulty: 'beginner',
    featuredImageUrl: '/assets/generated/monetization_blueprint_featured_1778177186388.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ser-2',
    title: 'Plan Your Visit',
    slug: 'plan-your-visit',
    description: 'Hours, walk-ins, groups, and everything first-timers ask about WoodBine.',
    categoryIds: ['visit-guide'],
    articleCount: 2,
    difficulty: 'beginner',
    featuredImageUrl: '/assets/generated/seo_supremacy_featured_1778177198400.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ser-3',
    title: 'Salt Lake & the Arts District',
    slug: 'salt-lake-arts-district',
    description: 'Local guides for neighbors, tourists, and anyone hungry near the hall.',
    categoryIds: ['local-food'],
    articleCount: 1,
    difficulty: 'beginner',
    featuredImageUrl: '/assets/generated/authentication_masterclass_featured_1778177212479.png',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const BLOG_POSTS = [
  {
    id: 'blog-1',
    categoryId: 'visit-guide',
    title: 'First Timer\'s Guide to WoodBine Food Hall',
    slug: 'first-timers-guide-woodbine',
    excerpt: 'Old hall, new flavors — here\'s how to walk in, order from multiple counters, and make the most of your first visit.',
    content: '## Key Takeaways\n\n- WoodBine is a warehouse food hall in Salt Lake\'s arts district.\n- Each vendor runs its own counter — order separately, eat together.\n- Walk-ins welcome; check hours before you come.\n\n## What to Expect\n\nWoodBine brings multiple independent vendors under one roof. Grab a seat in the communal dining area, explore the counters, and mix dishes from different kitchens on one table.\n\n## Plan Your Visit\n\nCheck our Visit & Connect page for hours, directions, and parking. Follow us for live music nights and seasonal menu drops.',
    authorName: 'Maya Chen',
    authorId: 'auth-1',
    viewCount: 8420,
    helpfulCount: 412,
    tags: ['visit', 'guide', 'salt-lake'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    metaTitle: 'First Timer\'s Guide to WoodBine Food Hall | Salt Lake',
    metaDescription: 'How to visit WoodBine — walk-ins, vendor counters, hours, and tips for your first trip to the hall.',
    featuredImageUrl: '/assets/generated/viral_blog_strategy_featured_1778177344526.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: 'blog-2',
    categoryId: 'vendor-spotlights',
    title: 'Counter Spotlight: The Coffee Program You\'ll Crave All Week',
    slug: 'counter-spotlight-coffee',
    excerpt: 'Our morning counter pulls single-origin shots and seasonal lattes that keep regulars lining up before work.',
    content: '## Why This Counter Matters\n\nEvery food hall needs a strong coffee anchor. Ours opens early, pulls dialed-in espresso, and pairs pastries from neighboring vendors.\n\n## What to Order\n\nStart with a honey-lavender latte or a straight single-origin pour-over. Ask about the rotating seasonal special.\n\n## Plan Your Visit\n\nFind the counter near the main entrance — perfect for a quick stop or the first round of a longer hall crawl.',
    authorName: 'Jordan Ellis',
    authorId: 'auth-2',
    viewCount: 5200,
    helpfulCount: 288,
    tags: ['vendor', 'coffee', 'spotlight'],
    type: 'blog',
    status: 'published',
    metaTitle: 'WoodBine Coffee Counter Spotlight',
    metaDescription: 'Meet the coffee counter at WoodBine food hall — what to order and when to visit.',
    featuredImageUrl: '/assets/generated/monetization_blueprint_featured_1778177186388.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: 'blog-3',
    categoryId: 'events',
    title: 'How to Host a Private Event at WoodBine',
    slug: 'host-private-event-woodbine',
    excerpt: 'Birthdays, team dinners, and launch parties — how to book the hall and curate a multi-vendor menu.',
    content: '## Why Host Here\n\nWoodBine\'s warehouse space and multiple vendors make it easy to feed a crowd without picking one cuisine.\n\n## What to Know\n\nReach out through our Visit & Connect page with your date, headcount, and vibe. We\'ll help coordinate counters and layout.\n\n## FAQ\n\n**Can we reserve the full hall?** Partial and full buyouts are available depending on the date.\n\n**Do vendors accommodate dietary needs?** Yes — mix counters for vegetarian, gluten-free, and other preferences.',
    authorName: 'Sam Ortiz',
    authorId: 'auth-3',
    viewCount: 3100,
    helpfulCount: 156,
    tags: ['events', 'private', 'catering'],
    type: 'blog',
    status: 'published',
    metaTitle: 'Private Events at WoodBine Food Hall',
    metaDescription: 'Book a private event at WoodBine — group dining, vendor coordination, and hall buyouts in Salt Lake.',
    featuredImageUrl: '/assets/generated/seo_supremacy_featured_1778177198400.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
  {
    id: 'blog-4',
    categoryId: 'local-food',
    title: 'Salt Lake\'s Arts District Is Having a Food Moment',
    slug: 'salt-lake-arts-district-food',
    excerpt: 'Between galleries, studios, and warehouse conversions, the neighborhood around WoodBine is worth a full evening.',
    content: '## Why This Neighborhood\n\nThe arts district blends walkable culture with independent food — WoodBine sits at the center as a hub for multiple vendors.\n\n## Build Your Night\n\nStart with dinner at the hall, catch a gallery opening nearby, and finish with dessert from a hall counter to go.\n\n## Plan Your Visit\n\nWe\'re easy to reach from downtown Salt Lake. Street parking and transit options are listed on our support page.',
    authorName: 'Jordan Ellis',
    authorId: 'auth-2',
    viewCount: 4800,
    helpfulCount: 201,
    tags: ['salt-lake', 'arts-district', 'local'],
    type: 'blog',
    status: 'published',
    metaTitle: 'Arts District Food Guide | Near WoodBine',
    metaDescription: 'Explore Salt Lake\'s arts district — food, culture, and WoodBine food hall in one evening.',
    featuredImageUrl: '/assets/generated/authentication_masterclass_featured_1778177212479.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
  },
];
