/**
 * [LAYER: INFRASTRUCTURE]
 * Specialized Seed Data for the WoodBine Blog.
 * 
 * This file contains high-fidelity, pillar-style blog content for the Journal.
 */
import { Timestamp } from 'firebase-admin/firestore';

export const BLOG_AUTHORS = [
  {
    id: 'auth-1',
    name: 'Leonardo DaBee',
    bio: 'Master of the canvas and the hive. 15 years experience in digital-physical hybrid art.',
    role: 'Master Artist',
    avatarUrl: '/assets/generated/leonardo_dabee_avatar_1778177134928.png',
    socialLinks: { twitter: '#', instagram: '#' },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'auth-2',
    name: 'Sarah Strategist',
    bio: 'Growth lead for top editorial platforms. Expert in content velocity and community building.',
    role: 'Editorial Director',
    avatarUrl: '/assets/generated/sarah_strategist_avatar_1778177148101.png',
    socialLinks: { twitter: '#', instagram: '#' },
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'auth-3',
    name: 'Professor Oak',
    bio: 'Renowned researcher and competitive TCG judge with over 25 years of tournament experience.',
    role: 'TCG Research Director',
    avatarUrl: '/assets/generated/professor_oak_avatar_1778177162886.png',
    socialLinks: { twitter: '#', instagram: '#' },
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export const BLOG_SERIES = [
  {
    id: 'ser-1',
    title: 'The Monetization Blueprint',
    slug: 'monetization-blueprint',
    description: 'A step-by-step guide to building a $100k/year creator business from scratch.',
    categoryIds: ['creator-strategies'],
    articleCount: 3,
    difficulty: 'intermediate',
    featuredImageUrl: '/assets/generated/monetization_blueprint_featured_1778177186388.png',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-2',
    title: 'SEO Supremacy 2026',
    slug: 'seo-supremacy-2026',
    description: 'Master the technical and semantic aspects of search in the age of generative AI.',
    categoryIds: ['creator-strategies'],
    articleCount: 2,
    difficulty: 'advanced',
    featuredImageUrl: '/assets/generated/seo_supremacy_featured_1778177198400.png',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-3',
    title: 'The Authentication Masterclass',
    slug: 'authentication-masterclass',
    description: 'Forensic techniques for verifying the authenticity of high-value TCG assets.',
    categoryIds: ['collecting-101'],
    articleCount: 3,
    difficulty: 'advanced',
    featuredImageUrl: '/assets/generated/authentication_masterclass_featured_1778177212479.png',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'ser-4',
    title: 'The Pro Circuit Handbook',
    slug: 'pro-circuit-handbook',
    description: 'A comprehensive guide to transitioning from casual play to the professional tournament circuit.',
    categoryIds: ['tcg-strategy'],
    articleCount: 4,
    difficulty: 'intermediate',
    featuredImageUrl: '/assets/generated/pro_circuit_handbook_featured_1778177228003.png',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export const BLOG_POSTS = [
  // --- EXISTING POSTS (Migrated for continuity) ---
  {
    id: 'blog-1',
    categoryId: 'creator-strategies',
    title: 'The 7 Pillars of a Viral Blog Strategy',
    slug: 'pillars-viral-blog-strategy',
    excerpt: 'Mastering the art of content velocity and emotional resonance to break through the noise of the modern web.',
    content: '## Beyond the Noise\n\nTo build a blog that resonates, you must move beyond mere information sharing. You need a strategy that balances value, personality, and platform dynamics.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 12450,
    helpfulCount: 890,
    tags: ['strategy', 'growth', 'viral'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    featuredImageUrl: '/assets/generated/viral_blog_strategy_featured_1778177344526.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  
  // --- FLAGSHIP TCG STRATEGY GUIDES ---
  {
    id: 'blog-9',
    categoryId: 'tcg-strategy',
    title: 'Blue-Eyes White Dragon: The Ultimate 2026 Competitive Decklist',
    slug: 'blue-eyes-ultimate-decklist-2026',
    excerpt: 'The legend returns with new support. Here is the full 55-card breakdown for the modern Yu-Gi-Oh! meta.',
    content: '## Historical Context & Meta Evolution (2002-2026)\n\nThe journey of the Blue-Eyes archetype is a microcosm of Yu-Gi-Oh! history. From its inception as the powerhouse vanilla in Legend of Blue Eyes White Dragon (2002) to its surprising World Championship win in 2016.\n\n## Full Card-by-Card Technical Breakdown\n\n### The Core Dragons\n* 3x Blue-Eyes White Dragon\n* 3x Blue-Eyes Alternative White Dragon\n* 3x Blue-Eyes Abyss Dragon\n\n## Advanced Play Patterns & Micro-Decisions\nA common mistake for new Blue-Eyes pilots is over-extending into Neo Blue-Eyes Ultimate Dragon. While flashy, the current 2026 meta is dominated by Hand Trap density.\n\n## Probability & Consistency Metrics\n* Chance to open a Level 8 Dragon + Support: 82.4%\n* Chance to resolve a Turn 1 Synchro Summon: 68.1%\n\n## Economic Landscape & Investment Liquidity\nFrom an investment perspective, Blue-Eyes is the S&P 500 of TCGs.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 32000,
    helpfulCount: 2100,
    tags: ['yugioh', 'decklist', 'blue-eyes'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    featuredImageUrl: '/assets/generated/blue_eyes_decklist_featured_1778177359287.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  
  // --- TCG STRATEGY EXPANSION ---
  {
    id: 'blog-27',
    categoryId: 'tcg-strategy',
    title: 'Magic: The Gathering - The 2026 Modern Horizons IV Meta Shift',
    slug: 'mtg-modern-horizons-iv-meta-shift',
    excerpt: 'Analyzing the forensic impact of "The Hive-Mind" mechanic on the competitive Modern landscape.',
    content: '## The Era of Hive-Mind\n\nModern Horizons IV has done the unthinkable: it has shifted the entire format towards a collaborative resource-sharing meta. We break down the top three decklists that are currently dominating the GPC.\n\n### Archetype Highlight: Dimir Symbiosis\nThis deck leverages the Hive-Mind mechanic to force opponents into sub-optimal trades. We analyze the mathematical "Stall-Point" and why you should never play your win-con before Turn 5.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 24500,
    helpfulCount: 1890,
    tags: ['mtg', 'modern', 'strategy'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/mtg_meta_shift_featured_1778177373758.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-28',
    categoryId: 'tcg-strategy',
    title: 'The Math of Mulliganing: A Forensic Study on Opening Hand Variance',
    slug: 'math-of-mulliganing-variance-study',
    excerpt: 'Quantifying the risk of the "bottom-heavy" hand. When to stay, and when to pray.',
    content: '## Deterministic Deck Filtering\n\nMost players treat the mulligan as a gut feeling. We treat it as a calculation. Using a sample size of 10,000 simulated games, we have mapped the success rate of various 5-card and 6-card combinations in the 2026 meta.\n\n### The "No-Land" Fallacy\nWe disprove the common myth that keeping a 1-land hand is always a losing play, provided your mana curve follows the Golden Ratio of TCG deckbuilding.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 41000,
    helpfulCount: 3200,
    tags: ['math', 'theory', 'pro-play'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-26',
    categoryId: 'tcg-strategy',
    title: 'The Path to Worlds: How the 2026 Qualifier Season has Redefined Pro Play',
    slug: 'path-to-worlds-2026-pro-play',
    excerpt: 'New tournament formats and higher prize pools: A deep dive into the evolution of the competitive circuit.',
    content: '## The Professionalization of Play\n\nCompetitive TCG play in 2026 has officially moved from game rooms to arenas. With the new "Global Pro Circuit" (GPC) structure, the path to the World Championship has never been more grueling—or more lucrative.\n\n### Technical Skill vs. Deck Choice\nWe analyze the "Skill-to-Variance" ratio of the 2026 Regional winners and discuss why the current meta rewards pilot mastery over "meta-deck" copying.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 42000,
    helpfulCount: 3800,
    tags: ['esports', 'pro-circuit', 'tournament'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-4',
    seriesPosition: 1
  },
  {
    id: 'blog-35',
    categoryId: 'tcg-strategy',
    title: 'The Travel Logistics of a Pro: Navigating the 2026 Tour',
    slug: 'pro-travel-logistics-2026',
    excerpt: 'Jet lag, deck security, and tournament nutrition: The unglamorous side of the professional circuit.',
    content: '## Living Out of a Suitcase\n\nBeing a pro isn\'t just about playing cards; it\'s about logistics. We break down the optimal travel schedule for the 2026 GPC and how to ensure your high-value decks arrive safely in international waters.\n\n### The "Deck Vault" Protocol\nWe analyze the security measures taken by top players to protect their assets while traveling through high-risk transit hubs.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 12000,
    helpfulCount: 890,
    tags: ['travel', 'pro-life', 'security'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-4',
    seriesPosition: 2
  },

  // --- COLLECTING 101 EXPANSION ---
  {
    id: 'blog-29',
    categoryId: 'collecting-101',
    title: 'Spotting Proxies: The Forensic Micro-Dot Test',
    slug: 'spotting-proxies-micro-dot-test',
    excerpt: 'Advanced authentication techniques for the modern collector. Don\'t let high-quality fakes ruin your portfolio.',
    content: '## The Arms Race of Authenticity\n\nAs printing technology evolves, so do proxies. In 2026, the "Light Test" is no longer sufficient. We introduce the Micro-Dot Test, a forensic method for identifying authentic ink patterns under 40x magnification.\n\n### The Rosette Pattern\nWe analyze the specific CMYK rosette patterns used by major TCG manufacturers and how to distinguish them from digital inkjet replication.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 52000,
    helpfulCount: 4500,
    tags: ['authentication', 'safety', 'collecting'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-3',
    seriesPosition: 1
  },
  {
    id: 'blog-33',
    categoryId: 'collecting-101',
    title: 'The Black Light Test: Identifying Modern Reprints',
    slug: 'black-light-test-reprints',
    excerpt: 'Why UV light is your best friend when distinguishing between 1999 originals and 2026 "Retro" reprints.',
    content: '## Glowing in the Dark\n\nThe chemical composition of card stock has changed drastically over three decades. We demonstrate how UV light reveals the "Optical Brighteners" used in modern reprints that are absent in vintage originals.\n\n### Forensic Comparison\nWe show side-by-side comparisons of authentic Base Set cards vs. high-end 2026 replicas under 365nm UV light.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 28000,
    helpfulCount: 2100,
    tags: ['uv-test', 'vintage', 'reprints'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-3',
    seriesPosition: 2
  },
  {
    id: 'blog-30',
    categoryId: 'collecting-101',
    title: 'Estate Planning for TCG Collectors: Protecting Your Legacy',
    slug: 'estate-planning-tcg-collectors',
    excerpt: 'How to legally and physically ensure your collection reaches the next generation intact.',
    content: '## Beyond the Vault\n\nA collection is more than just assets; it\'s a legacy. We sit down with legal experts specializing in digital and physical collectibles to discuss trusts, tax implications, and forensic cataloging.\n\n### The "Inheritance Crisis"\nWe address the common tragedy of high-value collections being sold for pennies by heirs who don\'t understand their value, and how to prevent it.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 15600,
    helpfulCount: 1200,
    tags: ['legal', 'finance', 'legacy'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },

  // --- CREATOR STRATEGIES EXPANSION ---
  {
    id: 'blog-31',
    categoryId: 'creator-strategies',
    title: 'Community Sovereignty: Moving Beyond Discord',
    slug: 'community-sovereignty-beyond-discord',
    excerpt: 'Why owning your audience platform is the most critical survival tactic of 2026.',
    content: '## The Platform Trap\n\nIn 2025, many creators lost their entire community due to arbitrary platform bans. In 2026, the trend is "Sovereignty." We explore how to build owned hubs that integrate directly with your personal brand.\n\n### Building the "Honeypot"\nWe analyze the WoodBine model for community engagement: shifting from reactive chat rooms to proactive, value-driven hubs.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 19800,
    helpfulCount: 1540,
    tags: ['community', 'strategy', 'ownership'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-32',
    categoryId: 'creator-strategies',
    title: 'Monetizing the Niche: The Archetype Newsletter Model',
    slug: 'monetizing-niche-archetype-newsletter',
    excerpt: 'How to build a $5k/month revenue stream by focusing on a single, high-passion niche.',
    content: '## The Riches are in the Niches\n\nStop trying to cover "all TCGs." We analyze a creator who built a six-figure business focusing exclusively on "Goblincore" decklists. The secret? Vertical integration.\n\n### The Conversion Funnel\nWe break down the funnel from free YouTube content to a premium, data-driven newsletter that players actually want to pay for.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 27400,
    helpfulCount: 2200,
    tags: ['monetization', 'newsletter', 'business'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-3',
    categoryId: 'creator-strategies',
    title: 'Scaling Beyond the First $10k',
    slug: 'scaling-beyond-first-10k',
    excerpt: 'You\'ve hit your first milestone. Now, how do you build a sustainable enterprise?',
    content: '## The Enterprise Shift\n\nMoving from a solo-creator to a business owner requires a fundamental change in mindset. We discuss delegating content creation and managing your forensic growth metrics.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 14500,
    helpfulCount: 1100,
    tags: ['business', 'growth', 'scaling'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-1',
    seriesPosition: 1
  },
  {
    id: 'blog-37',
    categoryId: 'creator-strategies',
    title: 'Affiliate Marketing Forensic: The Truth About Commissions',
    slug: 'affiliate-marketing-forensic',
    excerpt: 'Which TCG marketplaces offer the best returns for creators? We compare the big three.',
    content: '## The Affiliate Landscape\n\nNot all affiliate programs are created equal. We analyze the conversion rates and cookie durations of TCGPlayer, Cardmarket, and eBay in 2026.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 9800,
    helpfulCount: 710,
    tags: ['affiliate', 'revenue', 'monetization'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-1',
    seriesPosition: 2
  },
  {
    id: 'blog-38',
    categoryId: 'creator-strategies',
    title: 'The $100k Exit: Selling Your TCG Brand',
    slug: 'tcg-brand-exit-strategy',
    excerpt: 'When is it time to move on? How to value your digital assets for a clean acquisition.',
    content: '## The Final Milestone\n\nExiting a brand is the ultimate validation of your business model. We discuss how to prepare your books for a forensic audit by potential buyers.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 7600,
    helpfulCount: 540,
    tags: ['exit', 'business', 'acquisition'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-1',
    seriesPosition: 3
  },
  {
    id: 'blog-4',
    categoryId: 'creator-strategies',
    title: 'Technical SEO for the Modern Era',
    slug: 'technical-seo-modern-era',
    excerpt: 'Mastering the Core Web Vitals and semantic schema of 2026.',
    content: '## The Semantic Web\n\nSEO is no longer about keywords; it\'s about entity relationships. We break down how to optimize your blog for the new generative search engines.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 18900,
    helpfulCount: 1400,
    tags: ['seo', 'tech', 'search'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-2',
    seriesPosition: 1
  },
  {
    id: 'blog-39',
    categoryId: 'creator-strategies',
    title: 'Zero-Click Searches: Winning in the AI Snapshot Era',
    slug: 'zero-click-search-strategy',
    excerpt: 'How to maintain traffic when Google answers the question before the user even clicks.',
    content: '## Adapting to the Snapshot\n\nThe AI snapshot is the new Page 1. We discuss how to structure your content so it becomes the primary source for generative answers.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 12400,
    helpfulCount: 980,
    tags: ['seo', 'ai', 'google'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date(),
    seriesId: 'ser-2',
    seriesPosition: 2
  },
  {
    id: 'blog-16',
    categoryId: 'collecting-101',
    title: 'The Archival Vault: How to Store a $1M Card Collection',
    slug: 'archival-storage-guide',
    excerpt: 'Temperature, humidity, and UV: The technical science of preserving museum-grade TCG assets.',
    content: '## The Silent Killers: UV and Humidity\n\nMost collectors store their high-value cards in standard plastic sleeves, unaware that long-term outgassing can damage the card surface.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 8900,
    helpfulCount: 710,
    tags: ['preservation', 'safety', 'storage'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-17',
    categoryId: 'tcg-strategy',
    title: 'One Piece TCG: The Rise of the Revolutionary Army Archetype',
    slug: 'one-piece-revolutionary-army-guide',
    excerpt: 'Analysis of the OP-07 meta shift and the competitive viability of Belo Betty in 2026.',
    content: '## Shaking the Foundations\n\nThe One Piece TCG has seen unprecedented growth in 2025.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 15600,
    helpfulCount: 1200,
    tags: ['one-piece', 'decklist', 'anime'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-18',
    categoryId: 'creator-strategies',
    title: 'The AI Editor: Scaling a TCG Publication to 1M Visitors',
    slug: 'scaling-tcg-publication-ai',
    excerpt: 'How to use generative AI for SEO research without losing the enthusiast soul of your brand.',
    content: '## Efficiency vs. Authenticity\n\nIn 2026, the web is flooded with low-quality AI content.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 22000,
    helpfulCount: 1800,
    tags: ['ai', 'publishing', 'growth'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-19',
    categoryId: 'tcg-strategy',
    title: 'Disney Lorcana: The Ruby/Amethyst Bounce Meta (Set 5 Update)',
    slug: 'disney-lorcana-bounce-meta-set-5',
    excerpt: 'A deep dive into the most enduring archetype in Lorcana history and its Set 5 evolutions.',
    content: '## The Power of the Bounce\n\nRuby/Amethyst continues to be the gatekeeper of the Lorcana meta.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 12400,
    helpfulCount: 980,
    tags: ['lorcana', 'disney', 'decklist'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-20',
    categoryId: 'tcg-strategy',
    title: 'Lugia VSTAR: The Aerodynamic Engine of 2026',
    slug: 'lugia-vstar-strategy-2026',
    excerpt: 'How to pilot the most consistent acceleration engine in Pokémon TCG history.',
    content: '## The Return of the King\n\nLugia VSTAR has seen a resurgence in 2026.',
    authorName: 'Professor Oak',
    authorId: 'auth-3',
    viewCount: 18500,
    helpfulCount: 1450,
    tags: ['pokemon', 'decklist', 'lugia'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-21',
    categoryId: 'collecting-101',
    title: 'Artist Spotlight: The Hive-Sovereign Aesthetics',
    slug: 'hive-sovereign-artist-spotlight',
    excerpt: 'A masterclass in the digital-physical hybrid art style of the 2026 expansion.',
    content: '## The Soul of the Card\n\nWhat makes a card "museum-grade"?',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 11200,
    helpfulCount: 890,
    tags: ['art', 'interview', 'design'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-22',
    categoryId: 'collecting-101',
    title: 'Cleaning Cloudy Slabs: The Forensic Guide to Case Restoration',
    slug: 'cleaning-cloudy-slabs-guide',
    excerpt: 'How to remove scratches and haze from PSA and BGS cases without damaging the certificate.',
    content: '## The Clarity Crisis\n\nScratched cases can lower the perceived value of a card by 10-15%.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 31000,
    helpfulCount: 2800,
    tags: ['maintenance', 'grading', 'restoration'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-23',
    categoryId: 'creator-strategies',
    title: 'The 2026 TCG Correction: Buying the Dip in a Volatile Market',
    slug: 'tcg-market-correction-2026',
    excerpt: 'Market indices are down 15%. Is this a crash, or the greatest buying opportunity of the decade?',
    content: '## The Macro Perspective\n\nThe 2026 "Correction" was inevitable after the record-breaking highs of 2024.',
    authorName: 'Sarah Strategist',
    authorId: 'auth-2',
    viewCount: 28900,
    helpfulCount: 2100,
    tags: ['finance', 'investment', 'market'],
    type: 'blog',
    status: 'published',
    isFeatured: true,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-24',
    categoryId: 'collecting-101',
    title: 'The Forbidden Alchemy: The Secret History of Misprints and Errors',
    slug: 'tcg-misprint-history-lore',
    excerpt: 'From "No Damage" Ninetales to "Ghost Rare" Errors: Why the flaws are often worth more than the perfection.',
    content: '## The Value of the Flaw\n\nIn the TCG world, perfection is common, but error is unique.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 15400,
    helpfulCount: 1200,
    tags: ['lore', 'misprints', 'collecting'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  },
  {
    id: 'blog-25',
    categoryId: 'collecting-101',
    title: 'Museum-Grade Storage: Reviewing the 2026 Archival Pro Series',
    slug: 'archival-pro-series-review-2026',
    excerpt: 'We stress-test the newest climate-controlled display cases. Is the $1,500 price tag worth the protection?',
    content: '## Total Isolation\n\nThe 2026 Archival Pro Series promises a "Zero-Light, Zero-Humidity" environment for your slabs.',
    authorName: 'Leonardo DaBee',
    authorId: 'auth-1',
    viewCount: 9800,
    helpfulCount: 740,
    tags: ['review', 'tech', 'storage'],
    type: 'blog',
    status: 'published',
    isFeatured: false,
    featuredImageUrl: '/assets/generated/generic_tcg_strategy_1778177431609.png',
    createdAt: new Date(),
    updatedAt: new Date(),
    publishedAt: new Date()
  }
];
